CREATE TABLE "GCG_4401_SORT_CODES" (
 "RECORD_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_ID" UNIQUE USING 0,
 "REQUIREMENT_ID" INTEGER,
 "SORT_CODE" CHAR(10),
 "ADDED_BY" CHAR(8),
 "ADDED_AT" DATETIME );
