CREATE TABLE "GCG_4401_OPERATIONS" (
 "RECORD_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_ID" UNIQUE USING 0,
 "REQUIREMENT_ID" INTEGER,
 "OPERATION_ID" INTEGER,
 "DESCRIPTION" LONGVARCHAR,
 "TYPE" CHAR(10),
 "MODE" CHAR(30),
 "INSERT_TYPE" CHAR(10),
 "VALUE" CHAR(20),
 "COMMENTS" LONGVARCHAR,
 "ADDED_BY" CHAR(8),
 "ADDED_AT" DATETIME,
 "MODIFIED_BY" CHAR(8),
 "MODIFIED_AT" DATETIME );
